version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx 
    restart: unless-stopped 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/http:/srv/http:ro
      - nextcloud:/var/www/html:ro

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80"
    env_file:
      - .env
    environment:
      - TZ='Europe/Madrid'
      - WEBPASSWORD=$PIHOLE_PASSWORD
    volumes:
      - etc-pihole:/etc/pihole
      - etc-dnsmasqd:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN

  git:
    build: ./git
    image: haztecaso/git
    container_name: git
    restart: unless-stopped 
    ports:
      - "2222:22"
    volumes:
      - ./config/git/sshd_config:/etc/ssh/sshd_config:ro
      - ./config/git/authorized_keys:/home/git/.ssh/authorized_keys:ro
      - /srv/git:/srv/git

  cgit:
    build: ./cgit
    image: haztecaso/cgit
    container_name: cgit
    depends_on:
      - nginx
    restart: unless-stopped 
    volumes:
      - ./config/cgit/cgitrc:/etc/cgitrc:ro
      - /srv/git:/srv/git:ro

  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    depends_on:
      - nginx
    restart: unless-stopped 
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - /srv/vaultwarden:/data

  nextcloud:
    extends:
      file: nextcloud.yml
      service: nextcloud

volumes:
  etc-pihole:
  etc-dnsmasqd:
  git:
  nextcloud:
