version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx 
    restart: unless-stopped 
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_logs:/var/log/nginx
      - ./config/nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/http:/srv/http:ro
      - nextcloud:/var/www/html:ro

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80"
    env_file:
      - .env
    environment:
      - TZ='Europe/Madrid'
      - WEBPASSWORD=$PIHOLE_PASSWORD
    volumes:
      - etc-pihole:/etc/pihole
      - ./config/pihole/custom.list:/etc/pihole/custom.list:ro
      - etc-dnsmasqd:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN

  git:
    build: ./git
    image: haztecaso/git
    container_name: git
    restart: unless-stopped 
    ports:
      - "2222:22"
    volumes:
      - ./config/git/sshd_config:/etc/ssh/sshd_config:ro
      - ./config/git/authorized_keys:/home/git/.ssh/authorized_keys:ro
      - /srv/git:/srv/git

  cgit:
    build: ./cgit
    image: haztecaso/cgit
    container_name: cgit
    depends_on:
      - nginx
    restart: unless-stopped 
    volumes:
      - ./config/cgit/cgitrc:/etc/cgitrc:ro
      - /srv/git:/srv/git:ro

  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    depends_on:
      - nginx
    restart: unless-stopped 
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - /srv/vaultwarden:/data

  icecast:
    image: infiniteproject/icecast
    container_name: "icecast"
    env_file:
      - .env
    environment:
      - ICECAST_SOURCE_PASSWORD
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_RELAY_PASSWORD
      - ICECAST_MAX_SOURCES
      - ICECAST_ADMIN_EMAIL
      - ICECAST_HOSTNAME=icecast
    restart: unless-stopped

  liquidsoap:
    image: "savonet/liquidsoap:v1.4.3"
    container_name: "liquidsoap"
    depends_on: [icecast]
    command: "liquidsoap /script.liq"
    volumes:
      - "${MUSIC_DIR}:/music:ro"
      - "./config/liquidsoap/script.liq:/script.liq:ro"
    env_file:
      - .env
    environment:
      - ICECAST_SOURCE_PASSWORD
      - STREAM_NAME
      - STREAM_DESC
      - STREAM_URL
      - STREAM_MOUNTPOINT
    restart: unless-stopped

  nextcloud:
    image: nextcloud:21.0-fpm-alpine
    container_name: nextcloud
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis

  nextcloud_db:
    image: yobasystems/alpine-mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env
    volumes:
      - nextcloud_db:/var/lib/mysql

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped

  nextcloud_cron:
    image: nextcloud:21.0-fpm-alpine
    container_name: nextcloud_cron
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh

volumes:
  nginx_logs:
  etc-pihole:
  etc-dnsmasqd:
  git:
  nextcloud:
  nextcloud_db:
