version: "3.8"

services:
  nextcloud:
    image: nextcloud:21.0-fpm-alpine
    container_name: nextcloud
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis

  nextcloud_db:
    image: yobasystems/alpine-mariadb:latest
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env
    volumes:
      - nextcloud_db:/var/lib/mysql

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped

  nextcloud_cron:
    image: nextcloud:21.0-fpm-alpine
    container_name: nextcloud_cron
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh

volumes:
  nextcloud:
  nextcloud_db: 
