version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx 
    restart: unless-stopped 
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_logs:/var/log/nginx
      - ./config/nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/http:/srv/http:ro

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    depends_on: [nginx]
    restart: unless-stopped 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80"
    env_file:
      - .env
    environment:
      - TZ='Europe/Madrid'
      - WEBPASSWORD=$PIHOLE_PASSWORD
    volumes:
      - etc-pihole:/etc/pihole
      - ./config/pihole/custom.list:/etc/pihole/custom.list:ro
      - etc-dnsmasqd:/etc/dnsmasq.d/
      - pihole-logs:/var/log/
    cap_add:
      - NET_ADMIN

  git:
    build: ./images/git
    image: haztecaso/git
    container_name: git
    restart: unless-stopped 
    ports:
      - "2222:22"
    volumes:
      - ./config/git/sshd_config:/etc/ssh/sshd_config:ro
      - ./config/git/authorized_keys:/home/git/.ssh/authorized_keys:ro
      - /srv/git:/srv/git

  cgit:
    build: ./images/cgit
    image: haztecaso/cgit
    container_name: cgit
    depends_on: [nginx]
    restart: unless-stopped 
    volumes:
      - ./config/cgit/cgitrc:/etc/cgitrc:ro
      - /srv/git:/srv/git:ro

  meshcentral:
    build: ./images/meshcentral
    image: haztecaso/meshcentral
    container_name: meshcentral
    depends_on: [nginx]
    restart: unless-stopped 
    ports:
      - "5000:443"
    volumes:
        - ./config/meshcentral/config.json:/home/node/meshcentral/meshcentral-data/config.json
        - meshcentral-data:/home/node/meshcentral/meshcentral-data
        - meshcentral-files:/home/node/meshcentral/meshcentral-files

  syncthing:
    image: "syncthing/syncthing"
    container_name: "syncthing"
    environment:
      - PUID=1000
      - PĜID=1000
    volumes:
      - "syncthing:/var/syncthing"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped

volumes:
  nginx_logs:
  etc-pihole:
  pihole-logs:
  etc-dnsmasqd:
  git:
  meshcentral-data:
  meshcentral-files:
  syncthing:
