version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx 
    restart: unless-stopped 
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_logs:/var/log/nginx
      - ./config/nginx:/etc/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /srv/http:/srv/http:ro

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    depends_on: [nginx]
    restart: unless-stopped 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80"
    env_file:
      - .env
    environment:
      - TZ='Europe/Madrid'
      - WEBPASSWORD=$PIHOLE_PASSWORD
    volumes:
      - etc-pihole:/etc/pihole
      - ./config/pihole/custom.list:/etc/pihole/custom.list:ro
      - etc-dnsmasqd:/etc/dnsmasq.d/
      - pihole-logs:/var/log/
    cap_add:
      - NET_ADMIN

  git:
    build: ./images/git
    image: haztecaso/git
    container_name: git
    restart: unless-stopped 
    ports:
      - "2222:22"
    volumes:
      - ./config/git/sshd_config:/etc/ssh/sshd_config:ro
      - ./config/git/authorized_keys:/home/git/.ssh/authorized_keys:ro
      - /srv/git:/srv/git

  cgit:
    build: ./images/cgit
    image: haztecaso/cgit
    container_name: cgit
    depends_on: [nginx]
    restart: unless-stopped 
    volumes:
      - ./config/cgit/cgitrc:/etc/cgitrc:ro
      - /srv/git:/srv/git:ro

  meshcentral:
    build: ./images/meshcentral
    image: haztecaso/meshcentral
    container_name: meshcentral
    depends_on: [nginx]
    restart: unless-stopped 
    ports:
      - "5000:443"
    volumes:
        - ./config/meshcentral/config.json:/home/node/meshcentral/meshcentral-data/config.json
        - meshcentral-data:/home/node/meshcentral/meshcentral-data
        - meshcentral-files:/home/node/meshcentral/meshcentral-files

  icecast:
    image: infiniteproject/icecast
    container_name: "icecast"
    env_file:
      - .env
    environment:
      - ICECAST_SOURCE_PASSWORD
      - ICECAST_ADMIN_PASSWORD
      - ICECAST_RELAY_PASSWORD
      - ICECAST_MAX_SOURCES
      - ICECAST_ADMIN_EMAIL
      - ICECAST_HOSTNAME=icecast
    restart: unless-stopped

  liquidsoap:
    image: "savonet/liquidsoap:v1.4.3"
    container_name: "liquidsoap"
    depends_on: [icecast]
    command: "liquidsoap /script.liq"
    volumes:
      - "${MUSIC_DIR}:/music:ro"
      - "./config/liquidsoap/script.liq:/script.liq:ro"
    env_file:
      - .env
    environment:
      - ICECAST_SOURCE_PASSWORD
      - STREAM_NAME
      - STREAM_DESC
      - STREAM_URL
      - STREAM_MOUNTPOINT
    restart: unless-stopped

  syncthing:
    image: "syncthing/syncthing"
    container_name: "syncthing"
    environment:
      - PUID=1000
      - PĜID=1000
    volumes:
      - "syncthing:/var/syncthing"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped

  moodle_dl:
    build: ./images/moodle_dl
    image: haztecaso/moodle_dl
    container_name: moodle_dl
    restart: unless-stopped 
    volumes:
      - moodle_dl:/moodle_dl
      - ./config/moodle_dl/config.json:/moodle_dl/config.json

volumes:
  nginx_logs:
  etc-pihole:
  pihole-logs:
  etc-dnsmasqd:
  git:
  meshcentral-data:
  meshcentral-files:
  syncthing:
  moodle_dl:
